
services:
  app:
    image: server-service:latest
    container_name: server-service
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://nbAdaran:<db_password>@users.rmpyjrs.mongodb.net/server-db?appName=users

